image: wuennemannflorian/biocondapod:latest

additionalRepositories:
  - url: https://github.com/bioconda/bioconda-recipes

vscode:
  extensions: # based on nf-core.nf-core-extensionpack
    - esbenp.prettier-vscode # Markdown/CommonMark linting and style checking for Visual Studio Code